require("hop").setup({
    keys = "asdfgqwertzxcvb",
    quit_key = "<Esc>",
    perm_method = require("hop.perm").TrieBacktrackFilling,
    case_insensitive = true,
    jump_on_sole_occurrence = false,
    teasing = true,
    reverse_distribution = false,
    create_hl_autocmd = true,
    uppercase_labels = true,
    direction = nil,
    hint_position = require("hop.hint").HintPosition.BEGIN,
    hint_offset = 0,
    current_line_only = false,
    uppercase_labels = false,
    char2_fallback_key = "<Esc>",
    extensions = nil,
    multi_windows = false,
})
