[flags]
hide_avg_cpu = true
rate = 1000
current_usage = false
case_sensitive = false
temperature_type = "c"
default_widget_type = "proc"
hide_table_gap = true
disable_click = false
color = "default"
mem_as_value = true # can't decide
tree = false # can't decide
show_table_scroll_position = true
process_command = true
hide_time = true

[colors]
table_header_color="LightBlue"
widget_title_color="Green"
avg_cpu_color="Red"
cpu_core_colors=["LightMagenta", "LightYellow", "LightCyan", "LightGreen", "LightBlue", "LightRed", "Cyan", "Green", "Blue", "Red"]
ram_color="LightMagenta"
swap_color="LightYellow"
rx_color="LightCyan"
tx_color="LightGreen"
border_color="Gray"
highlighted_border_color="LightBlue"
text_color="Gray"
selected_text_color="Black"
selected_bg_color="Blue"
graph_color="Gray"
high_battery_color="green"
medium_battery_color="yellow"
low_battery_color="red"

[[row]]
    ratio=100
    [[row.child]]
        ratio=100
        type="cpu"
[[row]]
    ratio=90
    [[row.child]]
        ratio=60
        type="mem"
    [[row.child]]
        ratio=40
        type="net"
[[row]]
    ratio = 120
    [[row.child]]
        ratio=100
        type="proc"
        default=true

[net_filter]
is_list_ignored = true
list = ["virbr0.*"]
regex = true
case_sensitive = false
whole_word = false
